apiVersion: apps/v1
kind: Deployment
metadata:
  name:  main-http
  namespace: default
  labels:
    app:  main-http
  annotations:
    keel.sh/policy: force     # update policy (available: patch, minor, major, all, force)
    keel.sh/trigger: poll     # enable active repository checking (webhooks and GCR would still work)
    keel.sh/match-tag: "true" # only makes a difference when used with 'force' policy, will only update if tag matches :dev->:dev, :prod->:prod 
    keel.sh/approvals: "1"    # required approvals to update
    keel.sh/pollSchedule: "@every 1m"
spec:
  selector:
    matchLabels:
      app: main-http
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  main-http
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  main-http
        image:  khanhney/demo-github-action-keel:latest
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        #   limits:
        #     cpu: 100m
        #     memory: 100Mi