apiVersion: v1
kind: Service
metadata:
  name: main-http-service
  namespace: default
spec:
  selector:
    app: main-http
  type: NodePort
  ports:
  - name: main-http
    port: 3000
    targetPort: 3000
    protocol: TCP
    nodePort: 30003  #expose IP:port with minikube
    # minikube service main-http-service -n default 